// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package audiostreamer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AudioStreamClient is the client API for AudioStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioStreamClient interface {
	AudioStream(ctx context.Context, opts ...grpc.CallOption) (AudioStream_AudioStreamClient, error)
}

type audioStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioStreamClient(cc grpc.ClientConnInterface) AudioStreamClient {
	return &audioStreamClient{cc}
}

func (c *audioStreamClient) AudioStream(ctx context.Context, opts ...grpc.CallOption) (AudioStream_AudioStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AudioStream_ServiceDesc.Streams[0], "/audiostreamer.AudioStream/AudioStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &audioStreamAudioStreamClient{stream}
	return x, nil
}

type AudioStream_AudioStreamClient interface {
	Send(*AudioSample) error
	Recv() (*AudioSample, error)
	grpc.ClientStream
}

type audioStreamAudioStreamClient struct {
	grpc.ClientStream
}

func (x *audioStreamAudioStreamClient) Send(m *AudioSample) error {
	return x.ClientStream.SendMsg(m)
}

func (x *audioStreamAudioStreamClient) Recv() (*AudioSample, error) {
	m := new(AudioSample)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AudioStreamServer is the server API for AudioStream service.
// All implementations must embed UnimplementedAudioStreamServer
// for forward compatibility
type AudioStreamServer interface {
	AudioStream(AudioStream_AudioStreamServer) error
	mustEmbedUnimplementedAudioStreamServer()
}

// UnimplementedAudioStreamServer must be embedded to have forward compatible implementations.
type UnimplementedAudioStreamServer struct {
}

func (UnimplementedAudioStreamServer) AudioStream(AudioStream_AudioStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AudioStream not implemented")
}
func (UnimplementedAudioStreamServer) mustEmbedUnimplementedAudioStreamServer() {}

// UnsafeAudioStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioStreamServer will
// result in compilation errors.
type UnsafeAudioStreamServer interface {
	mustEmbedUnimplementedAudioStreamServer()
}

func RegisterAudioStreamServer(s grpc.ServiceRegistrar, srv AudioStreamServer) {
	s.RegisterService(&AudioStream_ServiceDesc, srv)
}

func _AudioStream_AudioStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioStreamServer).AudioStream(&audioStreamAudioStreamServer{stream})
}

type AudioStream_AudioStreamServer interface {
	Send(*AudioSample) error
	Recv() (*AudioSample, error)
	grpc.ServerStream
}

type audioStreamAudioStreamServer struct {
	grpc.ServerStream
}

func (x *audioStreamAudioStreamServer) Send(m *AudioSample) error {
	return x.ServerStream.SendMsg(m)
}

func (x *audioStreamAudioStreamServer) Recv() (*AudioSample, error) {
	m := new(AudioSample)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AudioStream_ServiceDesc is the grpc.ServiceDesc for AudioStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audiostreamer.AudioStream",
	HandlerType: (*AudioStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AudioStream",
			Handler:       _AudioStream_AudioStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/proto/audiostreamer.proto",
}
