// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: src/proto/audiostreamer.proto

package audiostreamer

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AudioSample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp string `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *AudioSample) Reset() {
	*x = AudioSample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_audiostreamer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSample) ProtoMessage() {}

func (x *AudioSample) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_audiostreamer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSample.ProtoReflect.Descriptor instead.
func (*AudioSample) Descriptor() ([]byte, []int) {
	return file_src_proto_audiostreamer_proto_rawDescGZIP(), []int{0}
}

func (x *AudioSample) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AudioSample) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_src_proto_audiostreamer_proto protoreflect.FileDescriptor

var file_src_proto_audiostreamer_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x22, 0x3f,
	0x0a, 0x0b, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x32,
	0x58, 0x0a, 0x0b, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x49,
	0x0a, 0x0b, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1a, 0x2e,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x1a, 0x1a, 0x2e, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x61,
	0x75, 0x64, 0x69, 0x6f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_audiostreamer_proto_rawDescOnce sync.Once
	file_src_proto_audiostreamer_proto_rawDescData = file_src_proto_audiostreamer_proto_rawDesc
)

func file_src_proto_audiostreamer_proto_rawDescGZIP() []byte {
	file_src_proto_audiostreamer_proto_rawDescOnce.Do(func() {
		file_src_proto_audiostreamer_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_audiostreamer_proto_rawDescData)
	})
	return file_src_proto_audiostreamer_proto_rawDescData
}

var file_src_proto_audiostreamer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_proto_audiostreamer_proto_goTypes = []interface{}{
	(*AudioSample)(nil), // 0: audiostreamer.AudioSample
}
var file_src_proto_audiostreamer_proto_depIdxs = []int32{
	0, // 0: audiostreamer.AudioStream.AudioStream:input_type -> audiostreamer.AudioSample
	0, // 1: audiostreamer.AudioStream.AudioStream:output_type -> audiostreamer.AudioSample
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_audiostreamer_proto_init() }
func file_src_proto_audiostreamer_proto_init() {
	if File_src_proto_audiostreamer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_audiostreamer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioSample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_audiostreamer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_audiostreamer_proto_goTypes,
		DependencyIndexes: file_src_proto_audiostreamer_proto_depIdxs,
		MessageInfos:      file_src_proto_audiostreamer_proto_msgTypes,
	}.Build()
	File_src_proto_audiostreamer_proto = out.File
	file_src_proto_audiostreamer_proto_rawDesc = nil
	file_src_proto_audiostreamer_proto_goTypes = nil
	file_src_proto_audiostreamer_proto_depIdxs = nil
}
